#!/usr/bin/env python3
"""
Generate Chain-of-Thought (CoT) instruction-completion pairs from real passed WordPress code.
Reads 40 diverse functions from data/phase1_extraction/output/passed/ (10+ repos) and
produces cot_real_code.json with step-by-step reasoning for each function.
"""

import json
import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
BASE = str(PROJECT_ROOT / "data" / "phase1_extraction" / "output" / "passed")

TARGET_REPOS = [
    "advanced-custom-fields.json",
    "woocommerce-payments.json",
    "wordpress-seo.json",
    "google-site-kit.json",
    "amp-wp.json",
    "cmb2.json",
    "wp-super-cache.json",
    "wordpress-develop.json",
    "contact-form-7.json",
    "query-monitor.json",
    "woocommerce-gateway-stripe.json",
    "wordpress-importer.json",
    "edit-author-slug.json",
    "performance-lab.json",
    "varnish-http-purge.json",
]

SELECTED_INDICES = [3,4,10,11,15,16,17,19,20,23,24,25,26,27,28,29,30,32,33,38,39,40,42,45,46,47,49,50,52,53,55,57,60,61,63,64,65,68,70,71]


def load_selected():
    all_complex = []
    for fname in TARGET_REPOS:
        with open(f"{BASE}/{fname}") as f:
            data = json.load(f)
        complex_fns = [
            fn for fn in data
            if fn.get("line_count", 0) > 20
            and (fn.get("sql_patterns") or fn.get("hooks_used") or len(fn.get("training_tags", [])) > 2)
        ]
        complex_fns.sort(key=lambda x: x.get("line_count", 0), reverse=True)
        all_complex.extend(complex_fns[:5])
    return [all_complex[i] for i in SELECTED_INDICES]


COT_DATA = [
    # 0: ACF::initialize
    {
        "instruction": "<wp_gen> Create a WordPress plugin main class initialize() method that defines plugin constants using a safe define wrapper, registers an activation hook, populates a comprehensive settings array with all plugin configuration defaults, includes required PHP files using a custom include helper, conditionally loads admin-only files behind is_admin(), uses version_compare for conditional feature flags, and registers WordPress actions and filters with specific priorities to wire up the plugin at the correct load order.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Constants are defined first via a custom $this->define() wrapper that uses defined() checks internally — this prevents re-definition errors if another plugin or test suite bootstraps this class twice.\n2. register_activation_hook(__FILE__, ...) is called during initialization rather than inside plugins_loaded because activation hooks must be registered before WordPress fires them; placing this call in an init-time method that runs on plugins_loaded is the earliest safe opportunity.\n3. The $this->settings array centralises all plugin defaults in one place — a well-known WordPress plugin architecture pattern. A single settings array consumed throughout the plugin avoids scattered option calls and makes defaults auditable in one location.\n4. Files are loaded via acf_include() rather than require_once directly. This helper resolves paths relative to ACF_PATH, preventing path manipulation issues and providing a single place to add future file-load instrumentation.\n5. Admin-only files are wrapped in is_admin() to avoid loading admin UI code during front-end requests, reducing memory footprint and preventing accidental execution of admin-specific globals.\n6. version_compare() is used to conditionally set a feature flag based on when the plugin was first installed, ensuring backward compatibility: users who installed before 6.3 retain the shortcode enabled by default.\n7. The ACF_PREVENT_PRO_LOAD constant check gives site owners an escape hatch to prevent the PRO bundle from loading — a common enterprise/testing pattern that avoids modifying plugin files.\n8. add_action() calls use specific priority values (4, 5) on 'init' to control execution order relative to other plugins that also hook into 'init' at the default priority 10.\n9. All hook callbacks are method references via array($this, 'method'), keeping the plugin testable — the object instance can be swapped in unit tests without global state.",
        "training_tags": ["plugin-initialization", "define-constants", "plugin_dir_path", "plugin_dir_url", "plugin_basename", "register_activation_hook", "settings-array", "conditional-admin-includes", "add_action", "add_filter", "is_admin-gating", "version_compare", "plugin-bootstrap"],
        "complexity": "complex",
    },
    # 1: acf_field_relationship::get_ajax_query
    {
        "instruction": "<wp_gen> Create a WordPress AJAX query handler method for a relationship field type that accepts user-supplied filter options (search string, post type, taxonomy, pagination), validates all user inputs against a field configuration allowlist to prevent privilege escalation, constructs WP_Query arguments with tax_query support, fires extensibility filters at three granularity levels, and returns results formatted for a Select2 AJAX response with grouped optgroups.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. wp_parse_args() merges user-supplied options against defaults, ensuring all keys exist downstream without null-checking every array access — a performance and readability win.\n2. The field configuration is loaded and validated before any query logic: if the field key is invalid, the function returns false immediately. This early-exit pattern prevents wasted processing and avoids operating on untrusted data.\n3. Post type validation uses array_intersect() against the field's allowed post types — a critical security boundary. Without this, an attacker could supply an arbitrary post_type via the AJAX request and bypass field-level restrictions.\n4. Post status is sourced exclusively from $field['post_status'] and never from user input. Post status filtering is a common privilege escalation vector (e.g., reading draft posts), so it must not be user-controlled.\n5. Taxonomy term validation checks both taxonomy name AND term value against the decoded allowlist. A partial check (taxonomy only) would still allow an attacker to enumerate terms from allowed taxonomies.\n6. wp_unslash() is applied to the search string because WordPress double-slashes $_POST values; not unslashing would corrupt search queries containing apostrophes or backslashes.\n7. Three levels of apply_filters() hooks (generic, by name, by key) follow ACF's naming convention and give developers fine-grained control over query modification without patching the plugin.\n8. When only one post type is being queried, the results are flattened from grouped to flat array. Select2 renders groups as <optgroup> elements, which are unnecessary for single-type results.\n9. The response includes a 'limit' key matching posts_per_page, which Select2 uses to determine whether more pages are available for infinite scroll.",
        "training_tags": ["AJAX query handler", "WP_Query via abstraction", "input validation", "allowlist validation", "capability boundary enforcement", "apply_filters extensibility", "tax_query construction", "post__in", "pagination", "select2 AJAX response", "wp_parse_args", "wp_unslash"],
        "complexity": "complex",
    },
    # 2: wordpress-seo save_postdata AJAX handler
    {
        "instruction": "<wp_gen> Create a WordPress AJAX handler method for saving post metadata that validates the POST request contains a valid integer post ID, checks user capability with current_user_can for the specific post, verifies a nonce with check_ajax_referer, applies wp_unslash before sanitizing all incoming data, supports multisite by switching to the correct blog, updates post meta and optionally re-inserts the post for slug changes, and responds with wp_send_json_success or wp_send_json_error with appropriate HTTP status codes.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The function validates $_POST['post_id'] exists and is a string before casting to integer. This two-step check prevents PHP notices from undefined key access and prevents type-juggling attacks where a non-string value could bypass the cast.\n2. wp_send_json_error('Bad Request', 400) uses the HTTP 400 status code to signal a malformed request to the JavaScript caller, which can distinguish network errors (5xx) from input errors (4xx).\n3. Capability check via current_user_can('edit_post', $post_id) is post-specific rather than a generic 'edit_posts' check — this ensures the user has permission for this specific post, not just the post type in general.\n4. check_ajax_referer() validates the nonce tied to this specific AJAX action. Placing this after the capability check means invalid nonces for unauthorized users don't consume unnecessary server processing.\n5. wp_unslash() is applied before sanitization because WordPress's magic quotes add slashes to $_POST values; sanitizing before unslashing would produce incorrect results for values containing backslashes or apostrophes.\n6. The multisite switch_to_blog() / restore_current_blog() pattern ensures post meta is saved to the correct site's database tables when called from a network context.\n7. Post re-insertion for slug changes uses wp_insert_post() rather than a direct $wpdb->update() — this fires all WordPress post hooks (transition_post_status etc.) and ensures cache invalidation happens correctly.\n8. do_action() hooks at key points allow third-party integrations (like Elementor) to hook into the save process without modifying core plugin files.",
        "training_tags": ["ajax-handler", "nonce-verification", "capability-check", "current_user_can", "check_ajax_referer", "wp_send_json_error", "wp_send_json_success", "wp_unslash", "input-validation", "multisite-check", "post-meta-saving", "apply_filters", "do_action"],
        "complexity": "complex",
    },
    # 3: wordpress-seo REST API route registration
    {
        "instruction": "<wp_gen> Create a WordPress REST API route registration method that registers multiple REST endpoints for a first-time configuration wizard with POST/GET/PUT methods, per-route permission callbacks using capability checks via class methods, strict argument schema validation (type, enum, required, sanitize_callback), and registers routes under a versioned plugin namespace constant.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Routes are defined as associative arrays rather than positional arguments, which improves readability and makes it easy to add new arguments without breaking callers.\n2. The permission_callback uses a method reference [$this, 'can_manage_options'] rather than an anonymous function. This allows unit testing of the permission logic independently and avoids closure serialization issues in some caching scenarios.\n3. Argument schemas include 'type', 'enum', 'required', and 'sanitize_callback' — WordPress's REST API automatically runs these for validation and sanitization before the callback fires, eliminating the need for manual validation inside the callback.\n4. Using 'enum' constraints for string arguments (e.g., 'company' | 'person') prevents injection of arbitrary values and communicates the valid domain of the argument to API consumers via the schema endpoint.\n5. The namespace is stored as a class constant rather than a magic string, ensuring all route registrations in the plugin use a consistent namespace and the value can be changed in one place.\n6. Separate routes for different operations (site representation, person social profiles, etc.) follow REST resource-oriented design: each resource has its own URL rather than overloading a single endpoint with an 'action' parameter.\n7. register_rest_route() is called inside a rest_api_init action hook (implied by the calling convention), ensuring routes are only registered when the REST API is actually initializing.",
        "training_tags": ["register_rest_route", "REST API", "permission_callback", "route registration", "argument schema validation", "REST API args", "namespace constants", "OOP WordPress patterns", "first-time configuration"],
        "complexity": "complex",
    },
    # 4: google-site-kit get_rest_routes
    {
        "instruction": "<wp_gen> Create a WordPress REST API controller method that returns an array of REST route definitions for a Google Site Kit module, with closure-based permission callbacks checking different capability levels (setup, authenticate, view dashboard), route callbacks that delegate to internal request dispatching via rest_do_request, argument sanitization callbacks, WP_Error returns on failure, and do_action hooks for telemetry.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Permission callbacks are defined as closures at the top of the function and referenced by multiple routes. This avoids duplicating capability check logic and makes the permission model visually scannable at a glance.\n2. Different routes use different permission levels ($can_setup vs $can_list_data) — fine-grained capability checking ensures read-only dashboard users cannot trigger setup operations.\n3. The 'sanitize_callback' in route args uses WordPress's built-in sanitize_text_field rather than custom validation, leveraging well-tested core sanitization that handles encoding edge cases.\n4. WP_Error objects are returned from callbacks (not thrown as exceptions) because the WordPress REST API framework expects WP_Error returns and automatically converts them to proper JSON error responses with HTTP status codes.\n5. Internal routes use rest_do_request() to dispatch sub-requests within the same WordPress process rather than making an HTTP call, avoiding authentication overhead and network latency for server-side data aggregation.\n6. do_action() hooks are fired at operation completion points, allowing third-party code to react to REST API operations (e.g., logging, cache invalidation) without modifying the plugin.\n7. Interface type-checking (instanceof) before calling optional methods ensures the module gracefully degrades when optional interfaces are not implemented, rather than producing fatal errors.\n8. Closures as callbacks (rather than string references) prevent global namespace pollution and keep the logic co-located with the route definition.",
        "training_tags": ["rest-api", "register_rest_route", "permission_callback", "WP_REST_Request", "WP_REST_Response", "WP_Error", "current_user_can", "capability-checks", "module-pattern", "exception-handling", "do_action", "sanitize_callback", "closures-as-callbacks"],
        "complexity": "complex",
    },
    # 5: google-site-kit Assets::get_assets
    {
        "instruction": "<wp_gen> Create a WordPress asset registration method that lazily initializes a list of plugin scripts and stylesheets using typed Script and Stylesheet objects, generates asset URLs from a versioned dist directory via a context abstraction, uses data callbacks to provide dynamic JavaScript configuration (nonces, REST URLs, plugin settings) evaluated at enqueue time, preloads REST API endpoints for instant data availability, and applies filters for extensibility.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The method uses an instance variable guard (if ($this->assets) return $this->assets) for lazy initialization — assets are only constructed once per request, preventing repeated instantiation of many Script/Stylesheet objects.\n2. Asset URLs reference a 'dist/assets/' directory resolved via $this->context->url(). Using a context object rather than plugin_dir_url(__FILE__) makes the asset base URL testable and overridable in tests or staging environments.\n3. Data callbacks are closures passed to Script_Data objects rather than evaluated immediately. This defers expensive operations (nonce generation, option reads) until the asset is actually enqueued, avoiding overhead on pages where these assets are not loaded.\n4. wp_create_nonce() is called inside a data callback to ensure the nonce reflects the currently authenticated user at enqueue time, not at class construction time, which could be earlier in the request lifecycle.\n5. REST API URLs are passed to JavaScript via esc_url_raw() (not esc_url()) because REST URLs may contain query parameters that esc_url() would strip as unsafe characters.\n6. REST preload paths use rest_do_request() to fetch data inline before the page renders, eliminating a round-trip AJAX request on the initial page load — a significant performance optimization for data-heavy admin pages.\n7. apply_filters() on the final assets array allows third-party plugins to add, remove, or modify assets without requiring a fork, following WordPress's open/closed extension pattern.",
        "training_tags": ["asset-registration", "wp-scripts", "wp-stylesheets", "apply_filters", "object-caching-via-instance-variable", "wp_create_nonce", "rest-api-preloading", "esc_url_raw", "data-callbacks", "lazy-initialization", "plugin-asset-management", "filter-extensibility"],
        "complexity": "complex",
    },
    # 6: google-site-kit Analytics_4::register
    {
        "instruction": "<wp_gen> Create a WordPress module registration method for a Google Analytics 4 integration that registers OAuth scopes, inline data, and feature metrics, constructs synchronization services with dependency injection, hooks into pre_update_option filters to detect settings changes and reset dependent data, registers cron event handlers with add_action, manages transients on settings change, and wires up REST API preloading.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Scope registration, inline data, and feature metrics are delegated to separate methods, keeping the register() method as a readable orchestrator — each concern has a single responsible method.\n2. pre_update_option filters intercept settings saves before they are committed, allowing the code to compare old vs. new values and conditionally reset dependent caches or tokens. Using pre_update_option is preferable to update_option because it fires before the value is written, enabling rollback if needed.\n3. Anonymous closures capture $this implicitly, allowing filter/action callbacks to invoke object methods without static method registry or global state.\n4. Transient deletion on settings change prevents stale cached data from being served after the user changes their configuration. The transient key is derived deterministically from the settings to ensure the right cache entry is invalidated.\n5. Cron event handlers are registered with add_action() rather than being scheduled inline — this separates scheduling logic from execution logic, making each independently testable.\n6. The Synchronize_Property and Synchronize_AdSenseLinked objects are constructed with dependency injection (passing $this, $user_options, $options), making them independently testable without a full module bootstrap.\n7. REST preload paths are registered during module init so that the Assets class can discover them when assembling the preload manifest, enabling zero-latency data for the module's React components.",
        "training_tags": ["module_registration", "add_action", "add_filter", "hooks_registration", "pre_update_option", "oauth_scopes", "data_reset_on_settings_change", "anonymous_closures_as_callbacks", "transient_management", "rest_api_preload", "cron_actions", "dependency-injection"],
        "complexity": "complex",
    },
    # 7: google-site-kit REST_Consent_Mode_Controller
    {
        "instruction": "<wp_gen> Create a WordPress REST API controller for a consent mode settings endpoint that registers GET and POST routes with separate capability requirements (manage_options vs update_plugins), returns current settings via WP_REST_Response, saves incoming settings with input validation, detects whether a related plugin is active and returns its activation URL, and uses apply_filters for extensible permission logic.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. GET and POST routes have different permission callbacks ($can_manage_options vs $can_update_plugins) — reading consent settings requires lower privilege than modifying them, following the principle of least privilege.\n2. The permission callbacks are closures referencing a Permissions class constant, keeping the authorization logic DRY and ensuring that if the capability name changes, it changes in one place.\n3. apply_filters() wraps the permission result, allowing site administrators to override permission logic for multisite or custom role scenarios without patching plugin code.\n4. Plugin detection and nonce URL generation happen inside the route callback rather than at registration time — this ensures the URL reflects the current plugin state at request time, not at init time.\n5. WP_REST_Response objects are returned rather than raw arrays. This allows the REST framework to attach proper Content-Type headers and HTTP status codes, and the response can carry additional HTTP headers.\n6. WP_Error is returned (not thrown) when permission is denied or input is invalid, because the REST framework converts WP_Error to a JSON error response with the correct HTTP status code automatically.\n7. Input from the request body is accessed via $request->get_param() rather than $_POST directly — this handles JSON request bodies, URL-encoded bodies, and properly decodes the content type.",
        "training_tags": ["REST API", "register_rest_route", "permission_callback", "current_user_can", "WP_REST_Response", "WP_REST_Request", "WP_Error", "apply_filters", "capability checks", "REST route args validation", "plugin detection", "consent mode"],
        "complexity": "complex",
    },
    # 8: amp-wp prepare_response
    {
        "instruction": "<wp_gen> Create an AMP response preparation method that validates the raw HTML response is a non-error 2xx HTML response, uses _doing_it_wrong for deprecated argument detection, runs the content through a configurable chain of AMP sanitizers (removing invalid elements, adding required AMP attributes, handling CSS), collects and deduplicates validation errors, optionally stores validation errors for later review, and returns either valid AMP HTML or the original response on fatal processing failure.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The method checks the HTTP status code at the start and only processes 2xx HTML responses. Processing error pages or non-HTML responses through the AMP sanitizer would corrupt them and produce unhelpful validation errors.\n2. _doing_it_wrong() is used to deprecate the 'validation_error_callback' argument, giving developers a clear migration message while still functioning correctly — the unset() ensures the deprecated arg has no effect.\n3. error_get_last() is captured at the start because PHP's DOMDocument::loadHTML() triggers E_WARNING on malformed HTML, which would overwrite any previous error. Capturing it early allows the code to detect DOM parsing failures accurately.\n4. The sanitizer chain is retrieved via apply_filters() rather than being hardcoded, making it possible to add, remove, or replace sanitizers for custom AMP configurations.\n5. Validation errors are keyed by a hash of the error data to deduplicate identical errors that occur multiple times in the document, keeping the error list manageable.\n6. The method returns the original $response on fatal processing failures rather than returning empty HTML, ensuring the page remains functional (as non-AMP) even when AMP processing encounters a critical error.\n7. Post-processing validation error storage is conditional on whether the URL has been registered for validation — this avoids storing errors for every page load and only records them when explicitly requested (e.g., during a validation scan).",
        "training_tags": ["AMP", "html-processing", "sanitizers", "validation-errors", "filter-hooks", "DOMDocument", "error-handling", "response-preparation", "_doing_it_wrong"],
        "complexity": "complex",
    },
    # 9: amp-wp store_validation_errors
    {
        "instruction": "<wp_gen> Create an AMP validation error storage method that normalizes the URL for consistent storage, uses md5() of the URL as a custom post slug to look up or create a custom post type entry, serializes validation errors as post meta with deduplication, updates taxonomy term relationships to reflect current error types and statuses, and cleans post caches after update.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. URL normalization is applied before md5() hashing to ensure URLs differing only by trailing slashes or query parameter order resolve to the same storage key, preventing duplicate entries.\n2. md5($url) is used as the post slug rather than sanitize_title($url). MD5 produces a fixed-length, URL-safe string regardless of URL length, whereas sanitize_title would truncate long URLs and potentially produce collisions.\n3. 'include_trashed' => true in the post lookup allows the code to restore a previously trashed validation record rather than creating a duplicate — important for URLs that cycle through validation status over time.\n4. Errors are stored as post meta rather than post content. Post meta supports structured array data (serialized by WordPress), whereas post content is a single text blob. Using meta also allows meta_query filtering.\n5. Deduplication of validation errors by computed key prevents the same error from being recorded multiple times for the same URL, keeping the stored error set minimal and accurate.\n6. Term relationships are updated after post meta to reflect the current set of error types — this enables taxonomy-based querying of which URLs have which classes of AMP errors.\n7. clean_post_cache() is called after updates to prevent stale object cache entries from serving outdated validation status to subsequent requests within the same page load.",
        "training_tags": ["AMP", "validation-errors", "custom-post-type", "post-meta", "taxonomy", "md5-slug", "url-normalization", "cache-invalidation", "post-storage-pattern"],
        "complexity": "complex",
    },
    # 10: AMP_Options_Manager::get_options
    {
        "instruction": "<wp_gen> Create a WordPress options manager static method that retrieves plugin options from the database, merges them with defaults (including defaults derived from theme support configuration), conditionally sets a 'configured' flag based on whether options were previously saved, validates the stored template mode is still supported, remaps deprecated option keys to their new equivalents, and applies a filter before returning.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The empty() check handles the case where get_option() returns an empty string (when the option has been saved as empty) rather than the false that would trigger the default parameter. Casting to array guarantees a consistent return type.\n2. Defaults are computed dynamically — AMP_Theme_Support::get_theme_support_args() is called at read time because theme support can change between requests (e.g., in multisite or theme-switching scenarios).\n3. The 'configured' flag is set based on whether $options was non-empty before merging with defaults. This correctly distinguishes a freshly-installed plugin from one that has been configured, without requiring a separate database flag.\n4. Template mode validation resets an invalid mode to the default rather than returning an error. Options can become invalid when a site changes themes or plugin configurations — a graceful fallback is preferable to breaking the site.\n5. Deprecated option remapping maps old option keys to their new equivalents, ensuring backward compatibility for sites with old options saved. This is preferable to a migration script because it handles all historical option states.\n6. apply_filters() at return time allows integrations to modify the returned options array — for example, a multisite plugin might override options based on network-level settings.",
        "training_tags": ["options-api", "get_option", "defaults-merging", "apply_filters", "template-mode-validation", "backward-compatibility", "static-method", "AMP-options"],
        "complexity": "medium",
    },
    # 11: cmb2 text_datetime_timestamp_timezone
    {
        "instruction": "<wp_gen> Create a CMB2 field sanitization method for a datetime-with-timezone field that handles repeatable field groups, applies wp_unslash to the raw value, parses the datetime string using date_create_from_format with a user-supplied format, converts to UTC using DateTimeZone, stores the UTC timestamp as an integer, and uses a static variable to accumulate UTC values across repeatable field iterations.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. static $utc_values accumulates values across multiple calls for repeatable fields. PHP static variables persist for the duration of the request, making them suitable as accumulators for values that must be collected across multiple field renders before being saved together.\n2. is_empty_value() short-circuits processing for blank fields, returning an empty string. Processing an empty string through date_create_from_format would produce a PHP warning and garbage output.\n3. wp_unslash() is applied before date parsing because WordPress's magic-quotes behavior can add backslashes to date strings from $_POST, which would corrupt date format strings (e.g., 'd/m/Y' becoming 'd\\/m\\/Y').\n4. date_create_from_format() is used instead of strtotime() because strtotime() applies heuristics that can misparse ambiguous date formats (e.g., '01/02/03' is ambiguous). Explicit format strings eliminate this ambiguity.\n5. try/catch around DateTimeZone construction protects against invalid timezone strings stored in user meta, which would otherwise throw an uncaught exception and produce a fatal error.\n6. The conversion to UTC timestamp (->getTimestamp() after setTimezone('UTC')) ensures that regardless of the user's local timezone, the stored value is always in a normalized, comparable form.\n7. The _check_repeat() mechanism handles the case where this sanitizer is called recursively for repeating field groups, delegating the repeat-loop logic to the base class to avoid duplication.",
        "training_tags": ["sanitization", "datetime-handling", "timezone-conversion", "static-variables", "exception-handling", "wp_unslash", "date_create_from_format", "DateTimeZone", "repeatable-fields", "CMB2"],
        "complexity": "medium",
    },
    # 12: CMB2_Type_File_List::render
    {
        "instruction": "<wp_gen> Create a CMB2 custom field type render method for a file list field that reads escaped meta values, iterates over stored attachment IDs and URLs, renders image previews using wp_get_attachment_image with a configurable size, outputs remove buttons with data-id attributes, and outputs a hidden input plus an Add/Upload button that opens the WordPress media library with query arguments passed as a JSON data attribute.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. $field->escaped_value() is used rather than accessing meta directly. CMB2's escaping layer applies context-appropriate escaping based on field type, ensuring all output is properly escaped without the render method needing to know the escaping rules.\n2. wp_get_attachment_image() is used for image previews rather than constructing an <img> tag manually. This function handles srcset, sizes attributes, and lazy loading automatically, and falls back gracefully when the attachment does not exist.\n3. The $img_size parameter is passed through to wp_get_attachment_image with a 'thumbnail' fallback — configurable image sizes allow the field to be used for both small previews and larger previews without code changes.\n4. $query_args for the media library uploader are stored in a data attribute as JSON, allowing the JavaScript uploader to read them and filter the media library (e.g., to show only images or only PDFs).\n5. Each file entry has a remove button with a data-id attribute containing the attachment ID. The JavaScript uses this to identify which entry to remove from the stored list without a server round-trip.\n6. The field renders a hidden input as the storage mechanism, populated by JavaScript when files are added or removed. Using a hidden input integrates with WordPress's standard form submission and meta saving without requiring a custom AJAX save handler.",
        "training_tags": ["custom-field-type", "file-upload", "media-library", "attachment-handling", "cmb2-framework", "wp_get_attachment_image", "i18n-esc_html__", "data-attributes", "list-rendering", "escaped-value-pattern"],
        "complexity": "medium",
    },
    # 13: cmb2 localize
    {
        "instruction": "<wp_gen> Create a WordPress admin script localization method with a static variable guard to prevent double-localization, building a data array with AJAX nonce, admin AJAX URL, debug flag, i18n strings using _x() with translation context, rich text editor capability detection via user_can_richedit, and code editor settings from wp_enqueue_code_editor, then calls wp_localize_script and applies a filter.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. static $localized = false prevents wp_localize_script() from being called multiple times if the method is invoked from multiple places in the same request. wp_localize_script() appends to the page's inline scripts, so calling it twice would inject the data object twice.\n2. wp_create_nonce() generates a request-specific nonce tied to the AJAX action. Including it in the localized data (rather than in a hidden input) makes it accessible to all JavaScript in the page context for AJAX requests.\n3. admin_url('/admin-ajax.php') resolves the correct AJAX endpoint URL regardless of whether the site is in a subdirectory or uses HTTPS. Hardcoding the URL would break on non-standard installations.\n4. _x() is used with translation context strings where the same English word might be translated differently depending on context (e.g., 'Add' as a button label vs. 'Add' as a mathematical operation).\n5. user_can_richedit() checks whether the current user has rich editor capability before passing TinyMCE configuration. Passing TinyMCE config to users who do not have the editor enabled would cause JavaScript errors.\n6. wp_enqueue_code_editor() both enqueues the code editor scripts AND returns configuration. Calling it here ensures the code editor is available when CMB2 needs it, with the settings bundled into the localized data.\n7. apply_filters() on the l10n array allows developers to add custom strings or modify defaults without having to fork CMB2.",
        "training_tags": ["wp_localize_script", "static_variable_guard", "wp_create_nonce", "apply_filters", "i18n", "_x_translation_context", "user_can_richedit", "wp_enqueue_code_editor", "admin_url"],
        "complexity": "medium",
    },
    # 14: CMB2_REST::register_cmb2_fields
    {
        "instruction": "<wp_gen> Create a static WordPress REST API field registration method for a custom meta framework that iterates over registered metaboxes, checks for a custom registration callback per box and delegates if callable, collects all post types and taxonomies associated with each box, deduplicates them using array_flip, and calls register_rest_field for each object type with unified get and update callbacks stored in static properties.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The per-box callback check (is_callable + call_user_func) allows individual metaboxes to override the default REST field registration logic — for example, a box might need custom field naming or special serialization.\n2. box_types() with a default of ['post'] normalizes boxes that do not specify an object type, ensuring all boxes are consistently associated with at least one type.\n3. array_flip() is used to deduplicate: flipping converts values to keys (where keys must be unique), then flipping back gives a unique value list. This is a PHP idiom for fast deduplication without array_unique's O(n) pass.\n4. Taxonomies are handled separately from post types because register_rest_field uses 'post' for post types but 'term' or the taxonomy name for taxonomies — conflating them would cause incorrect REST field registration.\n5. A single get_callback and update_callback are registered for all types, with the CMB2 box context passed via static properties. This avoids registering N closures for N types, reducing memory usage for plugins with many metaboxes.\n6. Static properties (self::$boxes) are used instead of instance properties because register_rest_field callbacks receive no context — a static lookup is the only way to retrieve the correct box inside the callback.",
        "training_tags": ["rest-api", "register_rest_field", "static-properties", "object-type-routing", "cmb2", "plugin-architecture", "custom-callback-pattern", "array_flip", "array_unique"],
        "complexity": "medium",
    },
    # 15: cmb2 columns_sortable_orderby
    {
        "instruction": "<wp_gen> Create a WordPress pre_get_posts hook callback for a CMB2 integration that adds sortable admin column support by checking the admin context, iterating over field configurations to find the field matching the current orderby parameter, then setting meta_key on the query and choosing meta_value_num for numeric field types versus meta_value for text fields.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. is_admin() guard at the top prevents this sorting logic from affecting front-end queries. pre_get_posts fires for all queries including AJAX and REST API requests, so the guard is essential to avoid unintended side effects.\n2. $query->get('orderby') is used rather than $_GET['orderby'] because WP_Query normalizes the orderby parameter, and using the query object's getter respects any filtering applied by other plugins.\n3. The loop checks $field['column'] emptiness and $field['column']['disable_sortable'] before comparing the field ID. This short-circuit evaluation means the more expensive string comparison only happens for fields that have column configuration.\n4. 'meta_value_num' is used for numeric field types rather than 'meta_value'. MySQL sorts 'meta_value' as a string, which would produce incorrect numeric ordering (10 < 9 lexicographically).\n5. The function modifies the passed $query object by reference and returns nothing, because pre_get_posts expects callbacks to modify the query object by reference, not return a new one.\n6. Field ID is used directly as the orderby key and meta_key, matching how sortable columns are registered. This coupling is intentional — the column and the sort are registered by the same class so the IDs are guaranteed to match.",
        "training_tags": ["sortable_columns", "pre_get_posts", "meta_value_num", "WP_Query manipulation", "admin-only hooks", "custom meta columns", "CMB2 integration", "is_admin check"],
        "complexity": "simple",
    },
    # 16: wp-super-cache is_bot_user_agent
    {
        "instruction": "<wp_gen> Create a WordPress caching plugin class method that detects whether a given user agent string belongs to a known web crawler or bot, using a comprehensive hardcoded list of bot agent substrings with source attribution comments for each vendor's documentation, and using stripos for case-insensitive substring matching with early return on first match.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The empty() guard returns false immediately for null or empty user agents. Many programmatic requests send no User-Agent header; treating them as bots would incorrectly skip caching for legitimate API consumers.\n2. stripos() is used instead of strpos() for case-insensitive matching. User-Agent strings from real bots vary in capitalization across versions and platforms, so case-insensitive matching is required for reliable detection.\n3. The bot list is hardcoded rather than stored in the database. For a caching plugin, database reads on every uncached request would be a significant performance penalty; the in-memory array has near-zero overhead.\n4. Source attribution comments (linking to Bing's official crawler documentation, ua-parser project) make the list auditable and maintainable. Future developers can verify entries and add new ones with confidence.\n5. The function returns true on the first match rather than collecting all matching patterns. For a boolean detection function, finding one match is sufficient, and early return minimizes the number of stripos() calls per request.\n6. The $ua parameter has a default of null and is checked with empty() rather than type-checking. This makes the function usable in contexts where the UA may not be available without requiring callers to check first.",
        "training_tags": ["user-agent-detection", "bot-detection", "stripos", "array-iteration", "class-method", "early-return", "input-validation", "caching-optimization"],
        "complexity": "simple",
    },
    # 17: wp-super-cache scossdl_off_get_options
    {
        "instruction": "<wp_gen> Create a WordPress CDN configuration options loader function that reads CDN settings from the database using get_option with strict false comparison, initializes missing options with add_option defaults, resolves the blog URL with untrailingslashit, splits comma-separated CNAME strings into trimmed arrays using array_map and array_filter, and applies a filter hook for extensibility.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Global variables are used because this is a legacy procedural plugin. The options are loaded into globals so they are accessible throughout the plugin's function set without passing parameters.\n2. false === get_option() (strict comparison) distinguishes between an option that does not exist (returns false) and one saved as an empty string (returns ''). Using == would treat both as falsy and overwrite intentionally-empty settings.\n3. add_option() (not update_option()) is used for initialization. add_option() is a no-op if the option already exists, making it safe to call on every request without overwriting user configuration.\n4. untrailingslashit(get_site_url()) normalizes the blog URL. CDN URL rewriting requires exact string prefix matching; a trailing slash mismatch would cause rewrites to fail.\n5. array_map('trim', ...) on the comma-separated CNAME list removes whitespace from user-entered values. Users frequently add spaces after commas when entering CDN hostnames.\n6. array_filter() removes empty strings that result from trailing commas in the stored value (e.g., 'cdn1.example.com,'). An empty CNAME in the list would produce malformed CDN URLs.\n7. apply_filters() on the final options array allows advanced users to override CDN settings programmatically, useful for multisite setups where different subsites need different CDN configurations.",
        "training_tags": ["options-api", "global-variables", "apply_filters", "add_option", "get_option", "untrailingslashit", "get_site_url", "array_map", "array_filter", "option-initialization-pattern", "cdn-configuration"],
        "complexity": "simple",
    },
    # 18: wpsc_register_post_hooks
    {
        "instruction": "<wp_gen> Create a WordPress cache invalidation hook registration function that uses a static boolean guard for idempotency, checks global cache_enabled and a WPLOCKDOWN constant before registering, then hooks into post lifecycle actions (publish, trash, edit, delete), comment events, and cron events with priority 0 for immediate cache clearing.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. static $done = false is the idempotency guard. This function is called from multiple code paths during plugin initialization; without the guard, hooks would be registered multiple times, triggering cache clearing multiple times per post save.\n2. Checking $GLOBALS['cache_enabled'] before registering hooks avoids adding overhead for sites where caching is explicitly disabled. If cache is off, there is no cache to clear and the hooks serve no purpose.\n3. The WPLOCKDOWN constant check prevents cache registration during maintenance mode. In lockdown, the site is intentionally serving static content and hook-triggered cache clearing would prematurely invalidate it.\n4. Priority 0 is used for post hooks rather than the default 10. Cache clearing should happen as early as possible in the action queue to prevent subsequent hooks from reading stale cache.\n5. Both wp_trash_post and before_delete_post are hooked because trashing (soft delete) and permanent deletion are separate events and both should invalidate the relevant cache entries.\n6. Comment hooks (comment_post, edit_comment) are included because new comments change the post's content visible to visitors, invalidating the cached HTML.\n7. The cron hook allows the cache to re-enable itself after a timed lockdown, supporting maintenance-window workflows.",
        "training_tags": ["static-variable-guard", "idempotent-registration", "add_action", "hook-registration", "cache-invalidation", "priority-management", "argument-count-in-hooks", "global-state-check", "defined-constant-check"],
        "complexity": "simple",
    },
    # 19: wp_insert_post
    {
        "instruction": "<wp_gen> Create the core WordPress wp_insert_post function that sanitizes all post fields, validates post author and post type, handles date parsing and normalization, fires before-insert filters, performs an INSERT or UPDATE to wp_posts using $wpdb->insert or $wpdb->update with prepared statements, updates post meta, fires post-insert action hooks including post-type-specific variants, cleans post caches, and returns the new post ID or WP_Error.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. $unsanitized_postarr captures the raw input before any sanitization for passing to filter hooks. Some hooks intentionally need access to the original unmodified data (e.g., for comparing with sanitized versions).\n2. wp_parse_args merges with defaults so all array keys exist downstream, eliminating repeated isset() checks throughout the function body.\n3. Post author validation checks that the author ID exists as a user. Inserting a post with a non-existent author ID would corrupt post metadata and break author archive queries.\n4. $wpdb->insert() and $wpdb->update() are used instead of $wpdb->query() with manually constructed SQL. These methods handle escaping internally via $wpdb->prepare(), preventing SQL injection even if upstream sanitization is bypassed.\n5. Multiple do_action hooks ('wp_insert_post', 'save_post', 'save_post_{$post_type}') fire to support the full hook hierarchy. Plugins may listen to the specific post type hook to avoid running on every post save.\n6. clean_post_cache($post_id) invalidates the object cache for the saved post, ensuring subsequent get_post() calls return fresh data rather than stale cached values.\n7. The $wp_error parameter controls whether the function returns false or a WP_Error object on failure. This backward-compatibility parameter allows callers written before WP_Error was available to continue working.",
        "training_tags": ["wp_insert_post", "sql:prepared_statements", "sql:targeted_select", "wpdb->insert", "wpdb->update", "do_action", "apply_filters", "clean_post_cache", "wp_error", "post-insertion", "capability-checks", "sanitization"],
        "complexity": "complex",
    },
    # 20: redirect_canonical
    {
        "instruction": "<wp_gen> Create the WordPress redirect_canonical function that detects when the requested URL should be redirected to a canonical URL, exempts POST requests, checks for valid preview nonces to avoid redirect loops, uses $wpdb->prepare for slug lookup queries to prevent SQL injection, normalizes permalink structure (trailing slash, www, index.php), and uses wp_redirect with 301 status, all wrapped behind an apply_filters hook for suppression.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The REQUEST_METHOD check at the top exempts POST, PUT, DELETE requests from canonical redirects. Redirecting a form submission would discard the POST data and break form processing.\n2. Preview nonce verification is checked before any redirect logic: if a valid preview nonce is present, the function returns early. Redirecting a valid preview URL would break the WordPress post preview system.\n3. $wpdb->prepare() is used for all database queries (e.g., looking up page slugs). Even though the values come from the URL, they are user-controlled and must be parameterized to prevent SQL injection.\n4. The redirect is only performed when $do_redirect is true, allowing callers (like unit tests or plugins) to call redirect_canonical($url, false) to get the canonical URL without triggering the actual redirect.\n5. wp_redirect() with status 301 is used for permanent redirects. Browser and search engine caches remember 301 redirects, improving performance for repeat visitors and consolidating SEO link equity.\n6. The function handles multiple URL normalization cases in a single pass rather than redirecting once per issue, preventing redirect chains.\n7. apply_filters('redirect_canonical', $redirect_url, $requested_url) allows plugins to suppress the redirect (return false) or modify the destination URL — essential for i18n plugins that manage URL structures.",
        "training_tags": ["redirect_canonical", "wp_redirect", "wpdb->prepare", "sql:prepared_statements", "nonce_verification", "canonical-url", "301-redirect", "apply_filters", "REQUEST_METHOD"],
        "complexity": "complex",
    },
    # 21: contact-form-7 form_html
    {
        "instruction": "<wp_gen> Create a Contact Form 7 method that renders a contact form as HTML, supporting configurable HTML attributes (id, name, title, class), generating unique sequential form IDs for accessibility, rendering ARIA attributes (aria-label, aria-describedby) only when the corresponding values are non-empty, including a hidden spam-prevention field, firing do_action hooks for content injection before and after the form, and escaping all output attributes with esc_attr.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. wp_parse_args() with defaults handles both string and array $options input. Contact Form 7 shortcodes can pass attributes as either format, and wp_parse_args normalizes both to an array.\n2. A sequential counter ensures each form on the page gets a unique HTML ID. Duplicate IDs are invalid HTML and break JavaScript/CSS selectors that rely on ID uniqueness.\n3. aria-label and aria-describedby are conditionally added only when the corresponding attributes (html_title) are non-empty. Adding empty aria attributes is worse than omitting them — screen readers would read empty labels aloud.\n4. All output attributes are passed through esc_attr() before insertion into the HTML string. Form IDs, names, and classes are user-configurable via shortcode, creating a potential XSS vector if unescaped.\n5. The hidden spam-prevention field is output inside the <form> tag to work with all submission handling. Placing it outside the form would cause browsers to omit it from the submitted data.\n6. do_action() hooks before and after the form fields allow third-party integrations to inject content (honeypot fields, GDPR notices) without requiring a core plugin modification.\n7. The 'raw_form' output option bypasses all processing and returns the form template in a <pre><code> block, useful for debugging template syntax.",
        "training_tags": ["security:output_escaping", "a11y:aria_attributes", "a11y:form_labels", "i18n:translation_functions", "form-rendering", "wp_parse_args", "esc_attr", "do_action"],
        "complexity": "medium",
    },
    # 22: CF7 scan_callback
    {
        "instruction": "<wp_gen> Create a Contact Form 7 regex scan callback that processes shortcode-like form tag syntax, handles the [[tag]] double-bracket escape by stripping one layer of brackets, extracts tag type and base type (trimming the * suffix), parses attributes with a dedicated method, fires apply_filters to allow custom tag modification, and populates a scanned tag registry used during form submission validation.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The double-bracket [[tag]] escape check is evaluated first. If matched, the outer brackets are stripped and the inner text returned verbatim. This must come first so the escape syntax is never processed as a real tag.\n2. trim($tag_type, '*') separates the basetype from the starred variant (e.g., 'text*' is a required text field). Storing both $tag_type and $tag_basetype allows dispatching on basetype while preserving the required-field flag.\n3. $this->parse_atts() handles attribute parsing — quoted strings, unquoted values, and boolean flags like 'required'. Delegating this to a dedicated method keeps scan_callback focused on orchestration.\n4. apply_filters('wpcf7_form_tag', ...) allows custom tag handlers to modify or replace the scanned tag data. This is the plugin's primary extension mechanism for adding new field types.\n5. The scanned tag is added to an internal registry (not just returned). This registry is consulted during form submission validation to know which fields to validate, ensuring the validation logic has access to all form tag configurations.\n6. The $replace flag controls whether the callback returns a string (for rendering) or adds to the registry (for scanning). This dual-mode design allows the same callback to serve both the scan pass and the render pass.",
        "training_tags": ["contact-form-7", "shortcode-scanning", "apply_filters", "tag-registry", "escape-syntax", "form-tag-processing", "regex-callback"],
        "complexity": "medium",
    },
    # 23: query-monitor template process
    {
        "instruction": "<wp_gen> Create a Query Monitor collector process method that resolves the active theme template file hierarchy by normalizing paths with cross-platform separator handling, applying array_unique to deduplicate the hierarchy, detecting block themes via get_block_theme_folders, resolving parent/child theme relationships by comparing stylesheet and template directories, and populating a typed data object with the final template path and theme metadata.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. QM_Util::standard_dir() normalizes directory separators (backslash to forward slash on Windows). WordPress's template functions return paths using the OS separator, but comparison requires a consistent format.\n2. array_unique() is applied to the template hierarchy before processing. The hierarchy can contain duplicates when multiple template tags resolve to the same file, and duplicates would produce redundant entries in the debug panel.\n3. The block theme folder detection (get_block_theme_folders()) handles the new block theme directory structure introduced in WordPress 5.9. Without this, block themes would show incorrect template paths in the debug output.\n4. Child vs. parent theme detection compares stylesheet_directory to template_directory. When they differ, a child theme is active; when equal, the theme has no parent. This determines how template inheritance is displayed.\n5. locate_template() results are stored with their full path to allow the debug panel to show which directory each template came from, crucial for diagnosing template override issues.\n6. The data object ($this->data) accumulates results rather than returning them. The collector pattern separates data collection from display, allowing the same data to be shown in multiple output formats (HTML panel, JSON API, CLI).",
        "training_tags": ["data-collection", "theme-template-hierarchy", "block-themes", "child-themes", "locate_template", "get_stylesheet_directory", "get_template_directory", "get_theme_root", "object-properties", "collector-pattern"],
        "complexity": "medium",
    },
    # 24: query-monitor QM_Collector_PHP_Errors::error_handler
    {
        "instruction": "<wp_gen> Create a custom PHP error handler for a debugging plugin that maps PHP error constants to severity level strings via switch/case, fires a do_action hook for each error, deduplicates repeated errors using MD5 hashing of message+file+line, conditionally captures backtraces based on a flag, applies wp_strip_all_tags to error messages, handles PHP 8.4 E_STRICT deprecation via version_compare, and stores classified errors in a structured data array.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The switch/case on $errno maps PHP's integer error constants to human-readable level strings. This decoupling means the display layer never needs to know PHP error constant values.\n2. do_action('qm/collect/new_php_error') fires for every error, allowing external plugins to react to PHP errors without hooking into the low-level set_error_handler mechanism. This is important for error monitoring integrations.\n3. MD5 of the concatenated message+file+line is used as a deduplication key. PHP errors inside loops can fire hundreds of times for the same issue; MD5 keying collapses these into a single entry with an occurrence count.\n4. debug_backtrace() is conditionally called based on $do_trace flag. Backtraces are expensive (memory and CPU); for errors in tight loops, disabling the trace prevents out-of-memory conditions.\n5. wp_strip_all_tags() is applied to the error message before display. Some error messages contain HTML (from objects using __toString()), which would be rendered as markup in the debug panel.\n6. version_compare(PHP_VERSION, '8.4', '>=') handles the removal of E_STRICT in PHP 8.4. Without this check, the handler would attempt to classify an unknown error constant.\n7. The error_reporting() check respects the site's configured error reporting level. A handler that ignores error_reporting would display errors that the site operator has intentionally suppressed.",
        "training_tags": ["php-error-handler", "do_action", "apply_filters", "version_compare", "error-suppression", "backtrace", "wp_strip_all_tags", "deduplication-by-md5-key", "static-property-caching", "PHP8.4-compatibility", "collector-pattern"],
        "complexity": "medium",
    },
    # 25: query-monitor QM_Collector_Cache::process
    {
        "instruction": "<wp_gen> Create a Query Monitor cache statistics collector process method that checks external object cache status via wp_using_ext_object_cache, safely introspects the global $wp_object_cache object using get_object_vars and array_key_exists to avoid fatal errors on implementations without hit/miss tracking, calculates a cache hit percentage, and stores the results in the collector's typed data object.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. wp_using_ext_object_cache() is called rather than checking $wp_object_cache directly. This WordPress function is the documented API for determining external cache status and handles edge cases like persistent object cache adapters that set the flag via wp-config.php.\n2. is_object($wp_object_cache) guards before any property access. The global may not be set on early requests or in unit tests; a null/false check prevents fatal errors.\n3. get_object_vars() is used to read cache properties rather than direct property access ($wp_object_cache->cache_hits). Direct access would throw a fatal error if the property does not exist in the specific object cache implementation being used.\n4. array_key_exists() checks before reading from $object_vars ensure the code degrades gracefully with object cache implementations that do not track hit/miss statistics.\n5. The hit percentage is calculated as (hits / (hits + misses)) * 100, with a guard against division by zero when both are zero (fresh page with no cache activity).\n6. method_exists() checks are used before calling optional methods on the cache object. Not all cache adapters implement the same interface, so optional method detection is required.",
        "training_tags": ["global-variable-access", "object-cache-inspection", "defensive-programming", "wp_using_ext_object_cache", "data-collector-pattern", "scalar-type-checking", "cache-statistics", "get_object_vars", "method_exists-check"],
        "complexity": "simple",
    },
    # 26: query-monitor determine_callback
    {
        "instruction": "<wp_gen> Create a Query Monitor utility method that resolves a WordPress hook callback (string, array, or closure) into a structured data object containing file path, line number, function name, and component, using PHP's ReflectionFunction and ReflectionMethod APIs, handling static string methods ('Class::method'), closures, invokable objects with __invoke, and legacy create_function callbacks with WP_Error returns on failure.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. String callbacks containing '::' are split into [class, method] arrays before reflection. PHP's ReflectionMethod requires a class name and method name separately; the '::' static method syntax is a shorthand that must be decomposed.\n2. ReflectionMethod is used for array callbacks ([object, 'method'] or ['Class', 'method']). ReflectionMethod provides getFileName() and getStartLine() without instantiating the class, making it usable for static methods.\n3. ReflectionFunction is used for closures and plain function strings. Closures have a getFileName() and getStartLine(), allowing the debug panel to show exactly where each anonymous function was defined.\n4. WP_Error is returned (rather than thrown) for unresolvable callbacks. The caller can check for WP_Error and display a 'callback not resolvable' message rather than crashing the debug panel.\n5. create_function() callbacks (a legacy PHP construct deprecated in PHP 7.2) are specially detected and flagged. They cannot be reflected meaningfully, so a descriptive placeholder is returned rather than a ReflectionException.\n6. Invokable objects (those with __invoke()) are handled via ReflectionMethod($object, '__invoke'). This covers cases like callable class instances used as hook callbacks in OOP-heavy plugin architectures.\n7. The result object (QM_Data_Callback) uses typed properties rather than a plain array, making the data structure self-documenting and allowing IDEs to type-check consumers of this method.",
        "training_tags": ["reflection_api", "callback_introspection", "closure_detection", "ReflectionMethod", "ReflectionFunction", "WP_Error_usage", "exception_handling", "type_detection", "static_methods", "invokable_objects", "legacy_create_function_handling"],
        "complexity": "complex",
    },
    # 27: woocommerce-gateway-stripe init
    {
        "instruction": "<wp_gen> Create a WooCommerce Stripe gateway plugin init action callback that conditionally loads an admin privacy class behind is_admin(), uses file_exists before requiring optional feature flag classes, requires all payment method class files, instantiates and registers gateway classes with WooCommerce's payment_gateways filter, initializes webhook handling, and sets up express checkout (Apple Pay/Google Pay) support.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. is_admin() gates the privacy class loading. The WC_Stripe_Privacy class contains admin-only GDPR data exporter/eraser registration; loading it on front-end requests would waste memory and potentially trigger premature admin function calls.\n2. file_exists() wraps the feature flags require_once because this file may not be present in all build configurations (e.g., split packages or partial installs). A missing file_exists check would produce a fatal error for those configurations.\n3. All payment method class files are required here (at init priority) rather than at plugins_loaded. WooCommerce's gateway filter runs during init, so all classes must be defined before that filter fires.\n4. The 'woocommerce_payment_gateways' filter is used to register gateways rather than directly instantiating them. This is WooCommerce's documented API for gateway registration, ensuring proper lifecycle management by WooCommerce core.\n5. Webhook handling is initialized separately because webhooks are received on dedicated endpoint URLs that exist independently of the checkout flow.\n6. Express checkout initialization is conditional on gateway availability and SSL status (checked inside the express checkout helper), following a defense-in-depth approach rather than checking only at display time.",
        "training_tags": ["plugin-initialization", "is_admin-gating", "file_exists-guard", "add_filter", "woocommerce-extension", "payment-gateway", "require_once", "feature-flags"],
        "complexity": "complex",
    },
    # 28: process_checkout_session
    {
        "instruction": "<wp_gen> Create a WooCommerce Stripe webhook handler method for checkout.session.completed events that refreshes a database cache with webhook payload data, maps the Stripe session to a WooCommerce order via stored meta, validates idempotency by checking if the order is already paid, validates payment intent status, saves payment metadata on the order before calling payment_complete, and logs all error conditions without rethrowing to ensure a 200 OK webhook response.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The database cache is refreshed at the start of the handler with the webhook payload data. Webhooks may arrive after the checkout page has cached a partial session object; refreshing ensures all subsequent reads reflect the final payment state.\n2. Order lookup uses custom post meta (the Stripe session ID stored on the order) rather than an order ID embedded in the webhook. The Stripe checkout.session object contains the metadata set when the session was created, making it the reliable link back to the WooCommerce order.\n3. The already-processed check (is_order_paid_or_cancelled()) provides idempotency — webhooks can be delivered multiple times by Stripe, so the handler must be safe to re-run on a previously completed order.\n4. Payment intent status validation ensures the handler only completes orders for successful payment intents. A checkout session can be created without payment (e.g., $0 orders), so the payment_intent field may be null.\n5. Order meta is saved (Stripe charge ID, payment intent ID) before calling payment_complete(). payment_complete() triggers email notifications; the meta must be present before emails are sent so recipients see complete information.\n6. All error cases log via WC_Stripe_Logger::log() rather than triggering exceptions. Webhook handlers must return a 200 OK response to prevent Stripe from retrying; logging errors without rethrowing achieves this.",
        "training_tags": ["webhook-handler", "woocommerce", "stripe", "payment-processing", "idempotency", "order-meta", "payment_complete", "cache-refresh", "error-logging"],
        "complexity": "complex",
    },
    # 29: should_show_express_checkout_button
    {
        "instruction": "<wp_gen> Create a WooCommerce Stripe express checkout helper method that determines whether to display Apple Pay/Google Pay buttons, checking in sequence: Stripe account connection, SSL requirement (bypassed in test mode), gateway enabled status, page type configuration (product/cart/checkout), and minimum cart amount, with verbose debug logging at each decision point.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. Account connection is checked first because it is a hard prerequisite — no other check makes sense if the Stripe account is not connected. Checking it first prevents unnecessary database reads for subsequent checks.\n2. SSL check uses is_ssl() combined with !$this->testmode. Test mode bypasses the SSL requirement intentionally, allowing developers to test on localhost. Production always requires SSL for PCI compliance.\n3. Each early return includes a debug log when verbose mode is enabled. Express checkout buttons are notoriously difficult to debug (they appear or disappear silently); detailed logging at each decision point is critical for merchant support.\n4. Page type checks (is_product(), is_cart(), is_checkout()) use WooCommerce's conditional functions rather than checking URLs or post types. These functions handle edge cases like custom shop templates and shortcode-embedded carts.\n5. The per-page-type configuration (show_on_product, show_on_cart) is checked against gateway settings, allowing merchants to enable express checkout selectively without code changes.\n6. Cart total minimum check is evaluated last because it requires loading the cart, which is the most expensive operation. Checking cheaper conditions first avoids loading the cart unnecessarily.",
        "training_tags": ["woocommerce", "stripe", "express-checkout", "apple-pay", "google-pay", "is_ssl", "capability-checking", "early-return", "conditional-display", "debug-logging"],
        "complexity": "medium",
    },
    # 30: wordpress-importer process_posts
    {
        "instruction": "<wp_gen> Create a WordPress importer process_posts method that applies a filter to the entire posts array before processing, skips posts with unregistered post types with an esc_html-escaped user notice, maps old author IDs to new IDs via a lookup table, detects previously imported posts to avoid duplicates, normalizes date formats, and fires filter hooks at each processing stage for extensibility.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. apply_filters('wp_import_posts') on the entire posts array allows pre-processing (e.g., filtering out certain post types) before the loop begins, rather than requiring hook consumers to process items individually.\n2. post_type_exists() validation with a user-visible printf notice is important for import usability. Simply skipping invalid post types silently would leave site owners confused about why some content was not imported.\n3. esc_html() is applied to post_title in the notice output. User-supplied content in imported XML could contain HTML that would be rendered as markup in admin notices without escaping.\n4. The author ID remapping step translates the import file's author IDs to the target site's user IDs. Without this, imported posts would be assigned to wrong or non-existent authors on the destination site.\n5. Duplicate detection via $this->processed_posts prevents re-importing content when an import is run multiple times or resumed after a timeout. Using a hash map (keyed by old post ID) makes the lookup O(1).\n6. wp_import_post_data_processed filter fires after all internal processing but before wp_insert_post, giving hook consumers access to the fully-prepared post array for final modifications.\n7. Date handling normalizes various date formats found in export files to MySQL datetime format, ensuring wp_insert_post receives valid date strings regardless of the export tool that generated the file.",
        "training_tags": ["post-import", "apply_filters", "post-type-validation", "author-mapping", "duplicate-detection", "wp_insert_post", "esc_html", "import-extensibility"],
        "complexity": "medium",
    },
    # 31: backfill_parents
    {
        "instruction": "<wp_gen> Create a WordPress importer backfill_parents method that resolves post parent relationships for orphaned imported posts by looking up both child and parent IDs in a processed_posts mapping table, using $wpdb->update with format specifiers to update post_parent directly in the database, and calling clean_post_cache for each updated post to invalidate stale object cache entries.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. A two-pass import strategy is required because XML files do not guarantee parent-before-child ordering. The first pass imports all posts (storing them in $this->processed_posts), and this backfill pass resolves parent links after all posts exist.\n2. $this->processed_posts acts as an ID mapping table: old_id => new_id. Both the child and parent IDs must be remapped from import-file IDs to the target site's auto-incremented IDs.\n3. $wpdb->update() is used rather than wp_update_post(). wp_update_post() triggers all post hooks and re-sanitizes content, which is unnecessary for a parent ID update and would significantly slow bulk imports.\n4. The $wpdb->update() format array ('%d', '%d') explicitly specifies integer types. This ensures the values are treated as integers in the SQL query, preventing type coercion issues with string IDs.\n5. clean_post_cache($local_child_id) is called after each update to invalidate the object cache. Without cache invalidation, subsequent get_post() calls might return the cached version with the old post_parent value.\n6. Both local_child_id and local_parent_id checks use isset() rather than array_key_exists(). For large imports, this is the faster check; both convey the same semantic for this use case since the values are set only as positive integers.",
        "training_tags": ["post-parent", "wpdb->update", "clean_post_cache", "sql:prepared_statements", "two-pass-import", "ID-mapping", "cache-invalidation"],
        "complexity": "medium",
    },
    # 32: edit-author-slug ba_eas_update_user_nicename
    {
        "instruction": "<wp_gen> Create a WordPress user profile save function that implements a full security chain: check_admin_referer for CSRF protection, current_user_can('edit_user', $user_id) for authorization, wp_unslash then sanitize_title for input sanitization, apply_filters for extensibility, remove_action/add_action around wp_update_user to prevent recursive profile_update hook invocation, and add_settings_error for failure reporting.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. check_admin_referer() validates both the nonce and that the request came from the admin dashboard, protecting against CSRF attacks. Without this, any site visitor could craft a POST request to change a user's nicename.\n2. current_user_can('edit_user', $user_id) uses the specific user ID rather than just 'edit_users'. This ensures editors can only modify their own profile (unless they have edit_users capability for arbitrary users).\n3. wp_unslash() before sanitize_title() is essential because WordPress's magic quotes add backslashes to POST data; without unslashing, a nicename like \"o'brien\" would be sanitized as \"o\\'brien\" and stored incorrectly.\n4. sanitize_title() is appropriate for URL slugs (nicenames are used in author archive URLs). It lowercases, removes special characters, and converts spaces to hyphens — exactly the transformations needed for a URL-safe slug.\n5. apply_filters('ba_eas_user_nicename', $nicename, $user_id) allows third-party plugins to modify or validate the nicename before save, enabling custom slug generation logic.\n6. remove_action/add_action around wp_update_user prevents recursive triggering of this same function from the profile_update hook that wp_update_user fires. Without the remove, the function would call itself indefinitely.\n7. WP_Error detection uses is_wp_error() rather than checking the return value type. wp_update_user returns either an integer (success) or WP_Error; is_wp_error() is the canonical WordPress way to distinguish these.\n8. add_settings_error() stores the error message for display after a redirect. WordPress admin notices require errors to be stored in a queue when they will survive a redirect.",
        "training_tags": ["nonce_verification", "capability_checks", "user_profile_update", "wp_error_handling", "sanitization", "apply_filters", "remove_action", "i18n", "wp_unslash", "profile_update_hook", "check_admin_referer"],
        "complexity": "complex",
    },
    # 33: ba_eas_register_admin_settings
    {
        "instruction": "<wp_gen> Create a WordPress Settings API registration function using add_settings_section, add_settings_field with label_for for accessibility, and register_setting with sanitize_callback, implementing settings for an author slug plugin that includes auto-update toggle, author slug structure selector (username/display-name/first-last-name/custom), and a conditionally visible custom base field.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. add_settings_section() groups related fields under a section with a description callback. Sections improve admin UI organization and allow fields to be conditionally hidden as a group.\n2. add_settings_field() registers each field with a label_for argument matching the HTML input's ID. This creates an accessible <label for='...'> association, ensuring clicking the label focuses the input for keyboard and screen reader users.\n3. register_setting() with a sanitize_callback is the critical security step. WordPress calls the sanitize callback before saving to the database, ensuring all user input is validated and sanitized regardless of how the form is submitted.\n4. The option group and option name are used consistently across all three Settings API functions. WordPress uses these to know which options belong together and which sanitize callback to apply to each.\n5. Conditional field registration (the custom base field only shows if the structure is 'custom') is handled by checking the current option value during registration. This avoids showing irrelevant fields and reduces user confusion.\n6. All field callback functions are referenced as strings (function names) rather than closures. Settings API callbacks are called repeatedly by WordPress; closures would create new function objects on each page load.\n7. i18n is applied to all user-visible strings (__(), _x(), esc_html_e()) enabling translation of the settings page into any language.",
        "training_tags": ["Settings API", "add_settings_section", "add_settings_field", "register_setting", "sanitize_callback", "label_for", "i18n", "admin settings page", "conditional settings", "plugin options"],
        "complexity": "medium",
    },
    # 34: ba_eas_get_nicename_by_structure
    {
        "instruction": "<wp_gen> Create a WordPress function that generates a user's URL slug (nicename) based on a configurable structure setting, using get_userdata to fetch user properties, a switch/case for structure dispatch (username, display_name, first_name, last_name, custom from user meta), sanitize_title for URL safety on all derived values, and apply_filters for extensibility.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. get_userdata() is called once at the start and the result is checked before proceeding. Failing fast with a return if user data is unavailable prevents null property access errors on all the subsequent case branches.\n2. A switch/case dispatch on the structure string is cleaner than an if/elseif chain for this many discrete options. Each case is a self-contained slug derivation with no fall-through logic needed.\n3. sanitize_title() is applied in every case. User meta values (display name, first name, last name) are user-controlled and may contain characters invalid in URLs; sanitize_title ensures the output is always a valid URL slug.\n4. The 'username' case uses user_login rather than user_nicename to produce a fresh slug from the username. This is the default behavior and serves as the safe fallback case.\n5. The 'custom' structure case reads user meta ('ba_eas_author_slug') which stores an admin-specified override. Using user meta allows per-user customization without schema changes.\n6. apply_filters('ba_eas_get_nicename_by_structure', $nicename, $user_id, $structure) fires after slug generation. Developers can override any slug programmatically without forking the plugin.\n7. The function accepts a $structure parameter rather than always reading from get_option(), making it testable in isolation and reusable for preview/validation scenarios before saving.",
        "training_tags": ["get_userdata", "apply_filters", "user-nicename", "switch-case-structure", "input-sanitization", "filter-hook", "early-return", "user-meta", "slug-generation", "sanitize_title"],
        "complexity": "simple",
    },
    # 35: ba_eas_auto_update_user_nicename
    {
        "instruction": "<wp_gen> Create a WordPress profile_update action callback that automatically syncs a user's nicename when their profile is saved, comparing the new computed slug with the stored value to skip unnecessary updates, temporarily removing and re-adding the profile_update hook around wp_update_user to prevent recursive invocation.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. The comparison of $new_nicename !== $userdata->user_nicename before calling wp_update_user avoids a database write when the nicename has not changed. wp_update_user is expensive (it updates the users table and fires hooks); skipping it when unnecessary improves performance during bulk profile updates.\n2. remove_action('profile_update', 'ba_eas_auto_update_user_nicename') before wp_update_user prevents infinite recursion. wp_update_user fires the profile_update action internally; without the remove, this function would call wp_update_user -> profile_update -> this function -> infinitely.\n3. add_action() is called after wp_update_user to re-register the hook. Any subsequent profile updates (e.g., from a later hook in the same request) will still trigger nicename auto-update.\n4. ba_eas_get_nicename_by_structure() is delegated to for the slug computation. Centralizing the slug logic in one function ensures auto-updates use the same algorithm as manual updates from the profile form.\n5. get_userdata($user_id) is called inside the callback (not reusing data from the outer scope) to get the authoritative current state. The profile_update hook fires after the user data has been saved, so outer scope data may be stale.\n6. The function accepts $user_id from the hook rather than using get_current_user_id(). This makes the function correct for bulk user updates (e.g., from WP-CLI or user import) where the user being updated is not the logged-in user.",
        "training_tags": ["wp_update_user", "profile_update hook", "remove_action/add_action loop prevention", "apply_filters extensibility", "get_userdata", "WP_User object", "bulk update pattern", "nicename sanitization"],
        "complexity": "simple",
    },
    # 36: performance-lab perflab_render_plugin_card
    {
        "instruction": "<wp_gen> Create a WordPress admin function that renders a plugin card UI for standalone performance plugins, showing plugin name, description, active/inactive status, and install/activate/deactivate action links gated behind current_user_can capability checks, with wp_nonce_url on all action URLs, esc_url/esc_html/esc_attr on all output, and aria-label on action links for accessibility.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. current_user_can('install_plugins') and current_user_can('activate_plugins') are checked before rendering action links. Showing action links to users who cannot act on them would be confusing and could leak information about the plugin's presence.\n2. wp_nonce_url() wraps the activate/install action URLs. Plugin activation and installation are irreversible operations; nonces ensure these actions can only be triggered from the admin page, not via CSRF.\n3. esc_url() is applied to all URL outputs, esc_html() to all text content, and esc_attr() to all HTML attribute values. Each escaping function is matched to its output context — using esc_html() on a URL would corrupt it.\n4. aria-label attributes on action links provide context for screen readers. A list of 'Activate' links without context would be indistinguishable; aria-label='Activate Plugin Name' disambiguates each link.\n5. The plugin active/inactive state controls which action link is shown. Showing both links simultaneously would be logically inconsistent; exactly one action is appropriate at any given state.\n6. Plugin data (name, description) is passed through __() for translation but escaping (esc_html()) is applied at output time, after translation, because translators might introduce HTML-unsafe characters.\n7. The card structure uses semantic HTML elements rather than generic <div> soup, improving accessibility and making the page structure parseable by assistive technologies.",
        "training_tags": ["i18n", "security:capability_checks", "a11y:aria_attributes", "security:output_escaping", "wp_nonce_url", "admin-UI", "plugin-card", "esc_url", "esc_html", "esc_attr"],
        "complexity": "medium",
    },
    # 37: webp_uploads_wrap_image_in_picture
    {
        "instruction": "<wp_gen> Create a WordPress image filter callback that wraps an <img> tag in an HTML <picture> element with <source> tags for WebP and AVIF format alternatives, using WP_HTML_Tag_Processor to reliably parse the img src attribute, adding type-attributed source elements with srcset for responsive image support, and preserving the original img as a fallback.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. WP_HTML_Tag_Processor is used instead of regex or DOMDocument for HTML manipulation. Regex-based HTML parsing is fragile (breaks on unexpected attribute ordering or values with HTML special characters); WP_HTML_Tag_Processor is WordPress's purpose-built, spec-compliant HTML parser introduced in WordPress 6.2.\n2. The function uses a filter hook to inject itself into the image rendering pipeline. This is preferable to modifying template files directly because it applies to all images regardless of where they are output.\n3. WebP and AVIF source elements are ordered with the more efficient format first. Browsers use the first matching <source>; placing AVIF before WebP ensures browsers that support both use the smaller AVIF file.\n4. The srcset attribute on <source> tags mirrors the img tag's srcset rather than just providing a single src. This preserves responsive image behavior (different sizes for different viewports) for the modern formats.\n5. type='image/webp' and type='image/avif' MIME type attributes are required for <picture> source selection. Without the type attribute, browsers cannot determine which source to use.\n6. Input sanitization is applied before insertion into the HTML output, preventing XSS through malformed image src attributes in the post content.\n7. The original <img> tag is preserved as a fallback inside <picture>. Browsers that do not support <picture> or the alternative formats will use the <img> tag's original src.",
        "training_tags": ["WP_HTML_Tag_Processor", "picture-element", "webp", "avif", "responsive-images", "filter-hook", "html-manipulation", "security:input_sanitization", "security:output_escaping", "performance-lab"],
        "complexity": "medium",
    },
    # 38: varnish-http-purge adminbar
    {
        "instruction": "<wp_gen> Create a WordPress admin bar integration function for a Varnish HTTP purge plugin that checks is_admin_bar_showing and current_user_can before adding nodes, creates a top-level node with a nonce-protected purge URL via wp_nonce_url, adds sub-nodes for purging the current URL and the full cache, and applies esc_url and esc_html to all output.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. is_admin_bar_showing() is checked at the start. The 'admin_bar_menu' action fires regardless of whether the bar is visible; the early return prevents unnecessary processing when the bar is hidden (e.g., for users who disabled it in profile settings).\n2. current_user_can() with the plugin's configurable capability respects capability customization. Site operators may grant cache purge access to editor-level users without granting full admin access.\n3. wp_nonce_url() on the purge URL prevents arbitrary cache purge requests. Without a nonce, any logged-in user (or a CSRF attacker) could trigger a full cache purge by visiting a crafted URL.\n4. esc_url() is applied to the nonce URL before passing it to $wp_admin_bar->add_node(). Even though wp_nonce_url() returns a valid URL, it could theoretically contain user-supplied data (from the current page URL) that needs escaping.\n5. esc_html() is applied to the node title strings. Admin bar titles that include site-specific content must be escaped to prevent XSS.\n6. The current-page purge and full-cache purge are separate sub-nodes. Merging them into a single 'purge all' action would be too aggressive for most cases; granular options give editors the minimum necessary cache control.\n7. The parent node is added unconditionally (as a UI anchor) but the capability check gates the functional child nodes, creating a consistent UI presence while keeping privileged actions gated.",
        "training_tags": ["admin-bar", "wp_nonce_url", "current_user_can", "esc_url", "esc_html", "capability-check", "varnish", "cache-purge", "is_admin_bar_showing"],
        "complexity": "medium",
    },
    # 39: varnish WP-CLI purge command
    {
        "instruction": "<wp_gen> Create a WP-CLI command class method implementing a Varnish cache purge command that accepts a URL positional argument with --wildcard and --debug flags, validates the URL with filter_var(FILTER_VALIDATE_URL), invokes the plugin's purge API, and reports success or failure using WP_CLI::success and WP_CLI::error with i18n-translated messages.",
        "cot_reasoning": "Step-by-step explanation of the key decisions in this code:\n1. WP-CLI commands receive $args (positional) and $assoc_args (named flags) as separate arrays, following the WP-CLI command method signature convention. Merging them would make the code less readable and harder to validate.\n2. The URL is validated with filter_var($url, FILTER_VALIDATE_URL) before passing to the purge API. An invalid URL passed to the HTTP purge request would generate a PHP warning and an unhelpful error; catching it early provides a clear user message.\n3. WP_CLI::error() is used for validation failures rather than WP_CLI::warning() + return. error() halts script execution and sets a non-zero exit code, which is essential for CI/CD pipelines that check the exit code to detect failures.\n4. WP_CLI::success() uses __() for the message string. CLI output is user-facing and should be translatable like admin UI strings; skipping i18n for CLI messages is a common oversight that this code correctly avoids.\n5. The --wildcard flag is passed through to the purge API rather than being handled in the CLI command itself. The plugin's purge logic already supports wildcard purging; the CLI flag is a thin wrapper that enables this existing capability.\n6. The --debug flag enables verbose logging inside the purge API. Surfacing this as a CLI flag allows operators running automated cache purges to enable detailed logging without modifying plugin settings permanently.",
        "training_tags": ["WP-CLI", "filter_var", "FILTER_VALIDATE_URL", "WP_CLI::success", "WP_CLI::error", "i18n", "cache-purge", "varnish", "CLI-command", "input-validation"],
        "complexity": "simple",
    },
]


def determine_complexity(fn):
    lines = fn.get("line_count", 0)
    has_sql = bool(fn.get("sql_patterns"))
    tags_count = len(fn.get("training_tags", []))
    if lines > 100 or has_sql or tags_count > 8:
        return "complex"
    elif lines > 40 or tags_count > 4:
        return "medium"
    return "simple"


def build_entry(fn, cot):
    complexity = cot.get("complexity") or determine_complexity(fn)
    tags = fn.get("training_tags") or cot.get("training_tags", [])
    return {
        "task_type": "wp_gen",
        "instruction": cot["instruction"],
        "response": fn["body"],
        "cot_reasoning": cot["cot_reasoning"],
        "source_repo": fn["source_repo"],
        "source_file": fn.get("source_file", ""),
        "function_name": fn["function_name"],
        "training_tags": tags,
        "complexity": complexity,
        "line_count": fn.get("line_count", 0),
    }


def main():
    selected = load_selected()
    assert len(selected) == len(COT_DATA), (
        f"Mismatch: {len(selected)} functions vs {len(COT_DATA)} CoT entries"
    )

    output = []
    for fn, cot in zip(selected, COT_DATA):
        output.append(build_entry(fn, cot))

    out_dir = PROJECT_ROOT / "data" / "phase3_cot" / "output"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = str(out_dir / "cot_real_code.json")
    with open(out_path, "w") as f:
        json.dump(output, f, indent=2, ensure_ascii=False)

    print(f"Written {len(output)} CoT entries to {out_path}")

    from collections import Counter
    complexities = Counter(e["complexity"] for e in output)
    repos = Counter(e["source_repo"] for e in output)
    total_lines = sum(e["line_count"] for e in output)

    print(f"\nComplexity breakdown: {dict(complexities)}")
    print(f"\nRepo coverage ({len(repos)} repos):")
    for repo, count in sorted(repos.items()):
        print(f"  {repo}: {count}")
    print(f"\nTotal lines of real code covered: {total_lines}")


if __name__ == "__main__":
    main()
